# Generated by Django 5.2.1 on 2025-05-18 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('due_date', models.DateTimeField(verbose_name='Срок исполнения')),
                ('notified', models.BooleanField(default=False, help_text='Ставить True после отправки уведомления через Celery', verbose_name='Уведомление отправлено')),
                ('telegram_user_id', models.BigIntegerField(help_text='Числовой идентификатор пользователя в Telegram', verbose_name='Telegram User ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='app.category', verbose_name='Категория')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
