# Generated by Django 5.2.1 on 2025-05-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_id_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled_task_id',
            field=models.CharField(blank=True, help_text='ID отложенной задачи в Celery (для отмены/переноса)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='Уведомление отправлено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='telegram_user_id',
            field=models.BigIntegerField(verbose_name='Telegram User ID'),
        ),
    ]
